version: 2.1

jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: [_site/]

  deploy:
    executor:
      name: node/default
      tag: '12'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "49:64:81:21:1f:23:76:37:30:f5:d5:18:2b:3a:28:8a"
      - run: cd /tmp/workspace/_site
      - run:
          name: Init repo
          command: |
            git init
            git config user.email "deployer@circle-ci"
            git config user.name "Deployer"
      - run:
          name: Commit
          command: |
            git add .
            git commit -m "Deploy"
      - run:
          name: Push
          command: |
            git remote add origin $CIRCLE_REPOSITORY_URL
            git push -f origin HEAD:gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

orbs:
  node: circleci/node@1.1
