version: 2.1

jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: [_site/]

orbs:
  node: circleci/node@1.1
